Include path in error when config parsing fails.
Currently, the message just reads:

  Error: Could not parse garden.yml as valid YAML

Which is not ideal when there are many garden.yml-s in the project. This
commit adds the absolute path to the failing garden.yml's enclosing dir.