fix: retry http requests in the tests
you can reproduce an error a lot with these steps:

garden dev --env remote
 > deploy --sync
 > test -f

```
   1) GET /
      respond with 200:
      Error: connect ECONNREFUSED 10.28.11.5:8080
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)

   2) POST /api/vote
      respond with 200:
      Error: connect ECONNREFUSED 10.28.11.5:8080
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
```

I suspect that it happens because the information where network packets
should be sent needs to replicate across all nodes in the kubernetes
cluster, so it might be that two seconds after the Pod has been
scheduled on one node, another node does not know about this IP address

I suspect that it happens because the information where network packets
should be sent needs to replicate across all nodes in the kubernetes
cluster, so it might be that two seconds after the Pod has been
scheduled on one node, another node does not know about this IP address
yet.