chore: add retry for flaky api call (#5383)
Add a retry regex in an attempt to fix test flakes that were causing >90% of our merge queue flakes recently.

The full error message looked like this:

```
  1) KubeApi
       helpers
         execInPod
           should exec a command in a Pod and return the output:
     Error: Error while performing Kubernetes API operation createNamespacedPod: ApiException

Response status code: 403
Kubernetes Message: pods "api-test-n122thrl" is forbidden: error looking up service account container-default/default: serviceaccount "default" not found
      at toKubernetesError (file:///home/circleci/project/core/src/plugins/kubernetes/retry.ts:142:10)
      at file:///home/circleci/project/core/src/plugins/kubernetes/api.ts:823:27
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at retry (file:///home/circleci/project/core/src/plugins/kubernetes/retry.ts:51:14)
      at requestWithRetry (file:///home/circleci/project/core/src/plugins/kubernetes/retry.ts:74:18)
      at pRetry.retries (file:///home/circleci/project/core/src/plugins/kubernetes/api.ts:986:9)
      at RetryOperation._fn (file:///home/circleci/project/core/node_modules/p-retry/index.js:56:20)
```